services:
  php:
    build:
      context: .
    volumes:
      - ./app:/var/www/html
    env_file:
      - .env
    networks:
      - symfony_app

  nginx:
    image: nginx:1-alpine
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - ./artifacts/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    networks:
      - symfony_app
  db:
    image: mysql:8.0.33
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "db_app:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    networks:
      - symfony_app

networks:
  symfony_app:

volumes:
  db_app:
