services:
  php:
    build:
      context: .
    volumes:
      - ./app:/var/www/html
    env_file:
      - .env

  nginx:
    image: nginx:1-alpine
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - ./artifacts/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
